sudo: required

language: c

services:
  - docker

before_install:
  - docker pull jlirochon/avr-toolkit

script:
  - docker run -v `pwd`/Firmware/Chameleon-Mini:/build jlirochon/avr-toolkit make
  - cd Firmware/Chameleon-Mini && tar -cjf firmware.tar.bz2 Chameleon-Mini.hex Chameleon-Mini.eep
