sudo: required

language: c

services:
  - docker

before_install:
  - docker pull jlirochon/avr-toolkit:0.0.1

script:
  - docker run -v `pwd`/Firmware/Chameleon-Mini:/build jlirochon/avr-toolkit:0.0.1 make
  - cd Firmware/Chameleon-Mini && tar -cjf firmware.tar.bz2 Chameleon-Mini.hex Chameleon-Mini.eep

deploy:
  provider: releases
  api_key:
    secure: cKuvKzNjBz/O+OWe/dqtSqLC/lzWHhipvnXNGo72QbYsJnS6rQ1BDCiWoVvta7qC6YGr0vGcUgIyn27p7GA8z9kEWLxejYPA3Vmsoh2bK7Y0NxPbTZ4mVPyA3WehARkHvzxl8Hbl28EL4XVt68QAQphLsYGxZzgJAjqtb9kJgI/5EKIZIa65cFYEjSrAeXnOzWe+eneUJ5h9enve2ueSKxK+GuXRptaRPluiWuq5PgV+4FtwMDxaPcJCUP87Zok5AmrUhW88/TtuZO7DUZ6uFhtbOWJR6GCXkNOl07mYNr7pMpFKsv3AEUvUOVVluJ4f59Jo3MYgEshPcaMNa0SBFlTL4pJZiTibJXWmDAZZHhJAuD5j8Dw6PZHM0AT4+8MWpYM/Ahhv/4S9HwZOlu0/Jv2+qiWETtjsmHB0p6oRkuXdwOzx4p6IBtEz2UnYInxIrudx4ThJq999QuHNAQ6S2SzoxlXr7Y8Exnx4GRtTZHQXFdbKTo2Q5hTclAmtyefHwrgmrhNfDWSPVd331tv8v2ZBqM2JUcaX5w7qqAdey1cs35yeEqrH+XEjQhJUw5AQA/s4czlyhDg8iacknlcz9eR/5pND1S/fZ61gtDEo8mlp9LUqMW4ghdaSWa57nr3PG469JbnyeG5grqd7BKkazlRY8RDntO3gHkVsBHp9Lto=
  file: Firmware/Chameleon-Mini/firmware.tar.bz2
  skip_cleanup: true
  on:
    repo: jlirochon/ChameleonMini-rebooted
    branch: automation
