version: 2
jobs:
  build:
    docker:
      - image: jlirochon/avr-toolkit:0.0.1
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: DEBUG where am I
          command: pwd && ls -la
      - run:
          name: Build Firmware
          command: |
            cd ~/build/Firmware/Chameleon-Mini
            make
      - persist_to_workspace:
          root: ~/build
          paths:
            - Firmware/Chameleon-Mini/Chameleon-Mini.hex
            - Firmware/Chameleon-Mini/Chameleon-Mini.eep

  publish:
    docker:
      - image: debian:stretch
    working_directory: ~/build
    steps:
      - attach_workspace:
          at: ~/build
      - run:
          name: DEBUG where am I
          command: pwd && ls -la

workflows:
  version: 2
  build_and_publish_wip:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: circle
